#[derive(Clone, Copy)]
#[repr(C, packed)]
pub struct Fat32BootSector {
    pub jump_instruction: [u8; 3],
    pub oem_name: [u8; 8],
    pub bytes_per_sector: u16,
    pub sectors_per_cluster: u8,
    pub reserved_sectors: u16,
    pub fat_count: u8,
    pub root_dir_entries: u16,
    pub total_sectors: u16,
    pub media_descriptor: u8,
    pub sectors_per_fat: u16,
    pub sectors_per_track: u16,
    pub head_count: u16,
    pub hidden_sectors: u32,
    pub total_sectors_large: u32,
    pub sectors_per_fat_large: u32,
    pub flags: u16,
    pub version: u16,
    pub root_dir_start: u32,
    pub fs_info_sector: u16,
    pub backup_boot_sector: u16,
    pub reserved0: u32,
    pub reserved1: u32,
    pub reserved2: u32,
    pub drive_number: u8,
    pub reserved3: u8,
    pub ext_signature: u8,
    pub serial_number: u32,
    pub volume_label: [u8; 11],
    pub system_id: [u8; 8],
    pub boot_code: [u8; 420],
    pub boot_signature: u16,
}
