[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-stork_os.json"

[target.x86_64-stork_os]
rustflags = [
    "-C",
    "panic=abort",
    "-C",
    "target-cpu=x86-64",
    "-C",
    "relocation-model=static",
    "-C",
    "link-args=-nostdlib",
    "-C",
    "link-arg=-Tlinker.ld",
]
