[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-stork_os.json"

[target.'cfg(all(target_arch = "x86_64", target_os = "none"))']
linker = "rust-lld"
rustflags = ["-C", "link-arg=--script=linker.ld"]
